import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("../engine", () => ({
  generateFilteredBoard: vi.fn(),
}));

import { generateFilteredBoard } from "../engine";
import { generateFilteredBoardId } from "../identifier";

const mockGenerateFilteredBoard = vi.mocked(generateFilteredBoard);

describe("generateFilteredBoardId", () => {
  beforeEach(() => {
    mockGenerateFilteredBoard.mockReset();
  });

  it("returns the board generated by the engine", async () => {
    mockGenerateFilteredBoard.mockResolvedValue("8-0622931ecfe9993de30355dae4");

    await expect(generateFilteredBoardId("Random")).resolves.toMatchObject({
      boardNumber: 8,
      id: "8-0622931ecfe9993de30355dae4",
    });
  });

  it("rejects an invalid engine result instead of changing practice focus", async () => {
    mockGenerateFilteredBoard.mockResolvedValue("not-a-board");

    await expect(generateFilteredBoardId("Strong2C")).rejects.toThrow(
      "invalid board identifier",
    );
  });
});
