// Copyright (c) 2026 The Yarborough Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Loaders for tests/engine-fixtures/ (regenerated by `pnpm fixtures:check` /
// `pnpm fixtures:accept`, src/engine/fixtures/export.ts; the record types
// are in src/engine/fixtures/types.ts and the exporter's hash of a printed
// form in src/engine/fixtures/hash.ts).  The files are read through Vite's
// `?raw` imports, so the tests need neither Node's file system nor its
// types.

import auctionSnapshotsText from "../../../../tests/engine-fixtures/auction-snapshots.jsonl?raw";
import decisionsText from "../../../../tests/engine-fixtures/decisions.jsonl?raw";
import meaningsText from "../../../../tests/engine-fixtures/meanings.jsonl?raw";
import modelExpressionsText from "../../../../tests/engine-fixtures/model-expressions.json?raw";
import rulesManifestText from "../../../../tests/engine-fixtures/rules-manifest.json?raw";
import vocabularyText from "../../../../tests/engine-fixtures/vocabulary.json?raw";

// The record types and the hash, re-exported for the tests that read them
// alongside the loaders.
export * from "../../fixtures/types";
export { fixtureHash, sha256Hex } from "../../fixtures/hash";

const TEXTS: Record<string, string> = {
  "auction-snapshots.jsonl": auctionSnapshotsText,
  "decisions.jsonl": decisionsText,
  "meanings.jsonl": meaningsText,
  "model-expressions.json": modelExpressionsText,
  "rules-manifest.json": rulesManifestText,
  "vocabulary.json": vocabularyText,
};

export function readFixtureText(name: string): string {
  const text = TEXTS[name];
  if (text === undefined) {
    throw new Error(`${name} is not a loaded fixture`);
  }
  return text;
}

export function readJsonFixture<T>(name: string): T {
  return JSON.parse(readFixtureText(name)) as T;
}

export function readJsonlFixture<T>(name: string): T[] {
  return readFixtureText(name)
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as T);
}
