// Copyright (c) 2026 The Yarborough Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Loaders for tests/engine-fixtures/ (generated by
// python/tests/export_fixtures.py; the schemas are in its docstrings), and the
// exporter's hash of a printed form: the first 16 hex characters of its
// sha256.  The files are read through Vite's `?raw` imports, so the tests
// need neither Node's file system nor its types; the hash is a small sha256
// in TypeScript for the same reason (and to stay synchronous).

import auctionSnapshotsText from "../../../../tests/engine-fixtures/auction-snapshots.jsonl?raw";
import meaningsText from "../../../../tests/engine-fixtures/meanings.jsonl?raw";
import modelExpressionsText from "../../../../tests/engine-fixtures/model-expressions.json?raw";
import rulesManifestText from "../../../../tests/engine-fixtures/rules-manifest.json?raw";
import vocabularyText from "../../../../tests/engine-fixtures/vocabulary.json?raw";

const TEXTS: Record<string, string> = {
  "auction-snapshots.jsonl": auctionSnapshotsText,
  "meanings.jsonl": meaningsText,
  "model-expressions.json": modelExpressionsText,
  "rules-manifest.json": rulesManifestText,
  "vocabulary.json": vocabularyText,
};

export function readFixtureText(name: string): string {
  const text = TEXTS[name];
  if (text === undefined) {
    throw new Error(`${name} is not a loaded fixture`);
  }
  return text;
}

export function readJsonFixture<T>(name: string): T {
  return JSON.parse(readFixtureText(name)) as T;
}

export function readJsonlFixture<T>(name: string): T[] {
  return readFixtureText(name)
    .split("\n")
    .filter((line) => line.length > 0)
    .map((line) => JSON.parse(line) as T);
}

// --- sha256 -------------------------------------------------------------

const K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
  0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
  0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
  0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
  0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

/** The sha256 of `text` (UTF-8), as lowercase hex. */
export function sha256Hex(text: string): string {
  const bytes = new TextEncoder().encode(text);
  const bitLength = bytes.length * 8;
  const padded = new Uint8Array(Math.ceil((bytes.length + 9) / 64) * 64);
  padded.set(bytes);
  padded[bytes.length] = 0x80;
  const view = new DataView(padded.buffer);
  view.setUint32(padded.length - 8, Math.floor(bitLength / 0x100000000));
  view.setUint32(padded.length - 4, bitLength >>> 0);
  const h = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c,
    0x1f83d9ab, 0x5be0cd19,
  ]);
  const w = new Uint32Array(64);
  const rotr = (x: number, n: number) => (x >>> n) | (x << (32 - n));
  for (let offset = 0; offset < padded.length; offset += 64) {
    for (let i = 0; i < 16; i++) {
      w[i] = view.getUint32(offset + i * 4);
    }
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >>> 3);
      const s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >>> 10);
      w[i] = (w[i - 16] + s0 + w[i - 7] + s1) >>> 0;
    }
    let [a, b, c, d, e, f, g, hh] = h;
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (hh + S1 + ch + K[i] + w[i]) >>> 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + maj) >>> 0;
      hh = g;
      g = f;
      f = e;
      e = (d + t1) >>> 0;
      d = c;
      c = b;
      b = a;
      a = (t1 + t2) >>> 0;
    }
    h[0] = (h[0] + a) >>> 0;
    h[1] = (h[1] + b) >>> 0;
    h[2] = (h[2] + c) >>> 0;
    h[3] = (h[3] + d) >>> 0;
    h[4] = (h[4] + e) >>> 0;
    h[5] = (h[5] + f) >>> 0;
    h[6] = (h[6] + g) >>> 0;
    h[7] = (h[7] + hh) >>> 0;
  }
  return [...h].map((word) => word.toString(16).padStart(8, "0")).join("");
}

/** `hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]`. */
export function fixtureHash(text: string): string {
  return sha256Hex(text).slice(0, 16);
}

// --- model-expressions.json ---------------------------------------------

export interface ModelExpressionsFixture {
  axioms: string[];
  named: Record<string, string>;
  hands: Record<string, string>;
  by_suit: Record<string, Record<string, string>>;
  NO_CONSTRAINTS: string;
}

// --- rules-manifest.json ------------------------------------------------

export type DescribedValue =
  | null
  | boolean
  | number
  | string
  | DescribedValue[]
  | { [key: string]: DescribedValue };

export interface ManifestPreferEntry {
  type: string;
  names: string[];
  conditional: boolean;
  order?: string;
  condition?: DescribedValue;
}

export interface ManifestConditionalPurpose {
  condition: DescribedValue;
  purpose: string | null;
  base: string | null;
}

export interface ManifestRule {
  name: string;
  mro: string[];
  category: string;
  purpose: string | null;
  purposes_per_call: Record<string, string | null>;
  conditional_purposes: ManifestConditionalPurpose[];
  conditional_purposes_per_call: Record<string, ManifestConditionalPurpose[]>;
  known_calls: string[];
  annotations: string[];
  annotations_per_call: Record<string, string[]>;
  annotations_for_call: Record<string, string[]>;
  fallback: number;
  requires_planning: boolean;
  forcing: boolean | null;
  explanation: string | null;
  explanations_per_call: Record<string, string>;
  preconditions: string[];
  preconditions_per_call: Record<string, string[]>;
  prefer: ManifestPreferEntry[];
  shared_constraints: DescribedValue;
  constraints: Record<string, DescribedValue>;
}

// --- vocabulary.json ----------------------------------------------------

export interface VocabularyFixture {
  purposes: {
    ORDER: string[];
    RANK: Record<string, number>;
    BY_SUIT: Record<string, string[]>;
    PREFERENCES: Record<string, [string, string | null][]>;
    CONDITIONS: Record<string, DescribedValue>;
  };
  annotations: string[];
  implies_artificial: string[];
  rule_categories: string[];
  positions: string[];
  strains: string[];
  strain_names: string[];
  suits: string[];
  majors: string[];
  minors: string[];
  calls: string[];
  levels: number[];
  points_tables: {
    suited: (number | null)[];
    notrump: (number | null)[];
    min_hcp_for_open: number;
  };
  rule_allowed_keys: string[];
}

// --- auction-snapshots.jsonl --------------------------------------------

export interface ViewSnapshot {
  last_call: string | null;
  annotations_for_last_call: string[];
  rule_for_last_call: string | null;
  annotations: string[];
  min_points: number;
  max_points: number;
  min_length: number[];
  max_length: number[];
  is_balanced: boolean;
  bid_suits: string[];
  unbid_suits: string[];
  contract_bid_suits: string[];
  could_have_more_points_than: Record<string, boolean>;
}

export interface GroupSnapshot {
  min_points: number;
  bid_suits: string[];
  unbid_suits: string[];
  annotations: string[];
}

export interface DroppedCall {
  call: string;
  category: string;
  rules: string[];
}

export interface AuctionSnapshot {
  dealer: string;
  vulnerability: string;
  calls: string;
  error?: string;
  legal_calls: string[];
  unbid_suits: string[];
  last_contract: string | null;
  us: GroupSnapshot;
  them: GroupSnapshot;
  everyone: GroupSnapshot;
  views: Record<string, ViewSnapshot>;
  bid_suit_naturally: Record<string, Record<string, boolean>>;
  first_natural_bidder: Record<string, string | null>;
  annotations_by_call: string[][];
  rule_by_call: (string | null)[];
  call_to_rule: Record<string, string>;
  selector_call_to_rule?: Record<string, string>;
  dropped_calls: DroppedCall[];
  forced_to_bid: boolean | { error: string };
}

// --- meanings.jsonl -----------------------------------------------------

export interface MeaningVariant {
  priority: string;
  meaning: string;
}

export interface MeaningRecord {
  call: string;
  rule: string;
  error?: string;
  variants?: MeaningVariant[];
  negations?: Record<string, number[]>[];
  constraints?: string;
  selector_constraints?: string;
  excluded_errors?: string[];
}

export interface MeaningsSnapshot {
  dealer: string;
  vulnerability: string;
  calls: string;
  error?: string;
  calls_and_rules?: MeaningRecord[];
}

/** The exporter's auction key: dealer, vulnerability and the calls string. */
export function auctionKey(
  dealer: string,
  vulnerability: string,
  calls: string,
): string {
  return `${dealer}|${vulnerability}|${calls}`;
}
