// Copyright (c) 2013 The SAYCBridge Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.
//
// A `HarnessBidder` that answers from the recorded fixtures instead of
// bidding, so the harness's text can be compared with the Python baselines
// before the TypeScript kernel exists.  If the harness prints the baseline
// byte for byte with this bidder, it will print it with the real one.
//
// Nothing here is edited by hand: `tests/engine-fixtures/` is generated by
// `python -m tests.export_fixtures`.

import decisionsText from "../../../../tests/engine-fixtures/decisions.jsonl?raw";
import snapshotsText from "../../../../tests/engine-fixtures/auction-snapshots.jsonl?raw";
import manifestText from "../../../../tests/engine-fixtures/rules-manifest.json?raw";
import type { CallHistory } from "../../core/callhistory";
import { Call } from "../../core/call";
import type { Hand } from "../../core/hand";
import type {
  HarnessBidder,
  HarnessRuleInfo,
  HarnessSelection,
} from "../harness";

/** One line of `decisions.jsonl` (the fields the harness needs). */
interface DecisionRecord {
  group: string;
  hand: string;
  calls: string;
  dealer: string;
  vulnerability: string;
  expected: string;
  call: string | null;
  rule: string | null;
  collision: {
    calls: string[];
    rules: string[];
    priorities: string[];
  } | null;
  /** Present only when `Bidder.call_selection_for` itself chose differently. */
  bidder_call?: string | null;
  bidder_rule?: string | null;
}

/** The fields of one `auction-snapshots.jsonl` record the harness needs. */
interface SnapshotRecord {
  dealer: string;
  vulnerability: string;
  calls: string;
  /**
   * The rule that interpreted each call of the auction, in call order.
   * `History.rule_for_last_call(LHO | Partner | RHO)` is its last three
   * entries, which is what the rules dump's fourth column holds.
   */
  rule_by_call?: (string | null)[];
}

interface RuleManifestEntry {
  name: string;
  requires_planning: boolean;
}

function parseJsonl<T>(text: string): T[] {
  return text
    .split("\n")
    .filter((line) => line.length)
    .map((line) => JSON.parse(line) as T);
}

/** The key both fixtures agree on: dealer, vulnerability and the auction. */
function auctionKey(
  dealer: string,
  vulnerability: string,
  calls: string,
): string {
  return `${dealer}|${vulnerability}|${calls}`;
}

function decisionKey(record: DecisionRecord): string {
  return `${record.hand}|${auctionKey(record.dealer, record.vulnerability, record.calls)}`;
}

/**
 * `[rule_for_last_call(LHO), ..(Partner), ..(RHO)]` for an auction: the last
 * three entries of the snapshot's `rule_by_call`, left-padded with nulls when
 * the auction is shorter than three calls.
 */
export function lastThreeRuleNames(
  ruleByCall: readonly (string | null)[],
): (string | null)[] {
  return [3, 2, 1].map((back) =>
    ruleByCall.length >= back ? ruleByCall[ruleByCall.length - back] : null,
  );
}

export class FixtureBidder implements HarnessBidder {
  private readonly selections = new Map<string, HarnessSelection | null>();
  private readonly ruleInfos: HarnessRuleInfo[];

  constructor() {
    const snapshots = new Map<string, SnapshotRecord>();
    for (const snapshot of parseJsonl<SnapshotRecord>(snapshotsText)) {
      snapshots.set(
        auctionKey(snapshot.dealer, snapshot.vulnerability, snapshot.calls),
        snapshot,
      );
    }

    for (const record of parseJsonl<DecisionRecord>(decisionsText)) {
      // `bidder_call` is recorded only when the bidder itself disagreed with
      // the step-by-step replay; the harness calls the bidder, so it wins.
      const callName =
        "bidder_call" in record ? (record.bidder_call ?? null) : record.call;
      const ruleName =
        "bidder_rule" in record ? (record.bidder_rule ?? null) : record.rule;
      if (callName === null) {
        // A falsy `call_selection`: no call, and no rule names recorded.
        this.selections.set(decisionKey(record), null);
        continue;
      }
      const snapshot = snapshots.get(
        auctionKey(record.dealer, record.vulnerability, record.calls),
      );
      if (!snapshot || !snapshot.rule_by_call) {
        throw new Error(
          `no auction snapshot with rule_by_call for ${record.dealer} ${record.vulnerability} "${record.calls}"`,
        );
      }
      this.selections.set(decisionKey(record), {
        call: Call.fromString(callName),
        ruleName,
        collision: record.collision,
        lastThreeRuleNames: lastThreeRuleNames(snapshot.rule_by_call),
      });
    }

    this.ruleInfos = (JSON.parse(manifestText) as RuleManifestEntry[]).map(
      (rule) => ({ name: rule.name, requiresPlanning: rule.requires_planning }),
    );
  }

  findCallFor(hand: Hand, callHistory: CallHistory): HarnessSelection | null {
    const key = `${hand.cdhsDotString()}|${auctionKey(
      callHistory.dealer.char,
      callHistory.vulnerability.name,
      callHistory.callsString(),
    )}`;
    if (!this.selections.has(key)) {
      throw new Error(`no recorded decision for ${key}`);
    }
    return this.selections.get(key) ?? null;
  }

  rules(): HarnessRuleInfo[] {
    return this.ruleInfos;
  }
}
